name: Node CI

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: pnpm/action-setup@v1.2.0
      with:
        node-version: ${{ matrix.node-version }}
    - name: pnpm install, build, and test
      run: |
        pnpm i
        pnpm run build
        pnpm run test
      env:
        CI: true
